- name: Check installed pipx packages
  ansible.builtin.command: pipx list --json
  register: pipx_list
  changed_when: false

- name: Install pipx packages
  ansible.builtin.command: >-
    pipx {{ 'upgrade' if item in ((pipx_list.stdout | from_json).venvs | default({})) else 'install' }} {{ item }}
  loop: "{{ pipx_packages }}"

- name: Install nvitop
  when: ansible_facts['system'] == 'Linux'
  block:
    - name: Check NVIDIA GPU
      ansible.builtin.shell: |
        test -e /proc/driver/nvidia/version || grep -q '^0x10de$' /sys/bus/pci/devices/*/vendor
      args:
        executable: /bin/bash
      register: nvidia_gpu_check
      changed_when: false
      failed_when: false
    - name: Install or upgrade nvitop
      ansible.builtin.command: >-
        pipx {{ 'upgrade' if 'nvitop' in ((pipx_list.stdout | from_json).venvs | default({})) else 'install' }} nvitop
      when: nvidia_gpu_check.rc == 0 or is_wsl
