# terminal
set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm:colors=256'

set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# colors
color_orange="colour166" # 208, 166
color_purple="colour134" # 135, 134
color_green="green" # 076, 070
color_blue="colour39"
color_yellow="colour220"
color_red="colour160"
color_black="colour232"
color_dark="colour238"
color_white="white" # 015

color_level_ok="$color_green"
color_level_warn="$color_yellow"
color_level_stress="$color_red"

# plugins settings
set -g @sysstat_cpu_view_tmpl 'CPU: #[fg=#{cpu.color}]#{cpu.pused}#[default]'
set -g @sysstat_mem_view_tmpl 'MEM: #[fg=#{mem.color}]#{mem.pused} #{mem.used}#[default]'
set -g @sysstat_cpu_color_low "$color_level_ok"
set -g @sysstat_cpu_color_medium "$color_level_warn"
set -g @sysstat_cpu_color_stress "$color_level_stress"
set -g @sysstat_mem_color_low "$color_level_ok"
set -g @sysstat_mem_color_medium "$color_level_warn"
set -g @sysstat_mem_color_stress "$color_level_stress"
set -g @gpu_low_fg_color "#[fg=$color_level_ok]"
set -g @gpu_medium_fg_color "#[fg=$color_level_warn]"
set -g @gpu_high_fg_color "#[fg=$color_level_stress]"

# status line
set -g status-bg "$color_dark"
set -g status-fg "$color_white"

# window status
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-current-style reverse

# status right
# if-shell 'type nvidia-smi 1>/dev/null 2>/dev/null' \
# 'set -g status-right "GPU: #{gpu_fg_color}#{gpu_percentage}#[default] | #{sysstat_cpu} | #{sysstat_mem} | #[fg=cyan]%m/%d %H:%M#[default] "' \
# 'set -g status-right "#{sysstat_cpu} | #{sysstat_mem} | #[fg=cyan]%m/%d %H:%M#[default] "'
set -g status-right "#h #[fg=cyan]%m/%d %H:%M#[default] "
set -g status-right-length 60

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-cpu'
# set -g @plugin 'samoshkin/tmux-plugin-sysstat'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
