fish_config_dir: "{{ xdg_config_home }}/fish"
fish_binary_path: >-
  {{
    brew_bin_dir ~ '/fish' if brew_binary_path is not none
    else 'fish'
  }}
fish_plugins_file: "{{ fish_config_dir }}/fish_plugins"
fish_plugins:
- jethrokuan/fzf
- jethrokuan/z
